// Generated by 'configure': C environment constants
#define LH_TARGET "amd64-linux-gnu"
#define LH_CCNAME "gcc"
#define LH_ABI_amd64
#define HAS_ASMSETJMP
#define ASM_JMPBUF_SIZE 72
// #define HAS_STRNCAT_S
// #define HAS_STRERROR_S
#define HAS_ALLOCA_H
#define HAS_STDBOOL_H
